server:
  port: 9030

spring:
  application:
    name: ratel-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

## knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN
  # 生产环境必须设置true,进行关闭
  production: false